In [33]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

df = pd.read_csv('student_scores_data.csv')
df.head(50)

    Hours  Percentage_Score
0     7.0              25.0
1    20.0              80.0
2    15.0              68.0
3    11.0              50.0
4     8.0              29.0
5    21.0              76.0
6     7.0              20.0
7    19.0              66.0
8    23.0              86.0
9    11.0              43.0
10   11.0              40.0
11   24.0              94.0
12   21.0              80.0
13    4.0              14.0
14    8.0              29.0
15   24.0              97.0
16    3.0               3.0
17   22.0              78.0
18   21.0              89.0
19    2.0               2.0
20   24.0              88.0
21   12.0              49.0
22    6.0              21.0
23    2.0               0.0
24   21.0              74.0
25    1.0               0.0
26    NaN              42.0
27   22.0              92.0
28    NaN              51.0
29   17.0              60.0
30   10.0              30.0
31   16.0              58.0
32   15.0              63.0
33   15.0               NaN
34   19.0              74.0
35   12.0              52.0
36   23.0              96.0
37   20.0              79.0
38    3.0              14.0
39    5.0              28.0
40   19.0               NaN
41    7.0              34.0
42   21.0               NaN
43    9.0              29.0
44    7.0               NaN
45   18.0              68.0
46    NaN              18.0
47   14.0              60.0
48   18.0              72.0
49    9.0              29.0

In [34]:
df.tail(50)

    Hours  Percentage_Score
50   21.0              86.0
51    2.0               4.0
52   20.0              88.0
53   15.0              51.0
54    7.0              27.0
55   12.0              50.0
56    8.0              42.0
57   15.0              55.0
58    3.0              13.0
59   14.0              57.0
60   17.0              77.0
61    4.0              16.0
62    NaN              68.0
63    8.0              22.0
64    4.0               6.0
65    2.0              17.0
66    6.0              26.0
67   22.0              86.0
68   10.0              32.0
69    4.0               NaN
70   22.0              83.0
71   18.0              69.0
72   12.0              46.0
73    2.0               2.0
74   10.0              30.0
75    4.0              24.0
76   14.0              55.0
77   16.0              65.0
78   15.0              64.0
79    8.0              30.0
80   14.0              65.0
81   23.0              98.0
82    8.0              38.0
83   21.0              93.0
84   16.0              65.0
85   13.0              48.0
86   18.0              63.0
87   15.0              52.0
88   21.0              90.0
89   24.0              90.0
90   13.0              58.0
91    9.0              42.0
92   15.0              66.0
93   13.0              43.0
94    1.0               0.0
95    7.0              22.0
96    9.0              26.0
97   24.0              86.0
98    NaN              12.0
99   12.0              39.0

In [35]:
df.shape

(100, 2)

In [36]:
df.describe()

           Hours  Percentage_Score
count  95.000000         95.000000
mean   13.031579         49.863158
std     6.861010         28.067779
min     1.000000          0.000000
25%     7.500000         27.500000
50%    13.000000         51.000000
75%    19.000000         73.000000
max    24.000000         98.000000

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Hours             95 non-null     float64
 1   Percentage_Score  95 non-null     float64
dtypes: float64(2)
memory usage: 1.7 KB

In [38]:
df.isnull().sum()

Hours               5
Percentage_Score    5
dtype: int64

In [39]:
df.head()

   Hours  Percentage_Score
0    7.0              25.0
1   20.0              80.0
2   15.0              68.0
3   11.0              50.0
4    8.0              29.0

In [40]:
df['Hours'].fillna(df['Hours'].mean(),inplace=True)

In [41]:
df['Percentage_Score'].fillna(df['Percentage_Score'].mean(),inplace=True)

In [42]:
df.isnull().sum()

Hours               0
Percentage_Score    0
dtype: int64

In [43]:
df.head(10)

   Hours  Percentage_Score
0    7.0              25.0
1   20.0              80.0
2   15.0              68.0
3   11.0              50.0
4    8.0              29.0
5   21.0              76.0
6    7.0              20.0
7   19.0              66.0
8   23.0              86.0
9   11.0              43.0

In [44]:
df = df.astype(int)

In [ ]:
df.head(10)

# import numpy as np

# np.random.seed(42)

# df['Attendance'] = np.random.randint(60, 101, len(df))

# df['Previous_Marks'] = np.random.randint(40, 96, len(df))   -->   yha hum aur column bhi create krr skte he kya pta aur achi accuracy aajaye

   Hours  Percentage_Score
0      7                25
1     20                80
2     15                68
3     11                50
4      8                29
5     21                76
6      7                20
7     19                66
8     23                86
9     11                43

In [46]:
from sklearn.model_selection import train_test_split

X = df[['Hours']]
y = df['Percentage_Score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [47]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [48]:
y_predict = model.predict(X_test)
y_predict

array([80.99956619, 57.27696298, 84.95333339, 69.13826459, 25.64682536,
       17.73929096, 21.69305816, 53.32319578, 41.46189417, 25.64682536,
       80.99956619, 37.50812697,  5.87798935, 57.27696298, 49.36942857,
       29.60059256, 53.32319578, 61.23073018, 80.99956619, 61.23073018,
       45.41566137, 80.99956619, 49.36942857, 80.99956619, 13.78552375,
       92.8608678 , 73.09203179, 33.55435976, 41.46189417, 45.41566137,
       92.8608678 , 53.32319578, 49.36942857])

In [49]:
y_test

83    93
53    51
70    83
45    68
44    49
39    28
22    21
80    65
10    40
0     25
18    89
30    30
73     2
33    49
90    58
4     29
76    55
77    65
12    80
31    58
55    50
88    90
26    42
42    49
69    49
15    97
40    49
96    26
9     43
72    46
11    94
47    60
85    48
Name: Percentage_Score, dtype: int64

In [52]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_predict)
n = X.shape[0]
p = X.shape[1]
adjust_score = 1 - ((1 - r2) * (n - 1) / (n - p - 1))

In [53]:
r2

0.74823093546091

In [54]:
adjust_score

0.7456618633737764

In [56]:
print(model.coef_)
print(model.intercept_)

[3.9537672]
-2.029545055979618

In [55]:
import pickle

with open('Predict_score.pkl' , 'wb') as f:
    pickle.dump(model , f)